#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $AZEROTHDIR = "/home/wowowner/azerothcore";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $startpath = $ENV{'PATH'};
my $newpath = "$AZEROTHDIR/exec:$startpath";
my $exists = "";

# Set ENV vars
$ENV{'PATH'} = $newpath;
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep authserver|grep -v grep`;

# check if Azeroth Auth server is running
if ($running ne "")
{
	print ("Auth server already running...\n");
	exit (0);
}

while (-1)
{
	chdir $AZEROTHDIR;
	# check if World Server process is running
	$running=`ps ax|grep authserver|grep -v grep`;
	if ($running eq "")
	{
		print "Auth Server not running\n";
		# See if they want the server started
		if (! -f "$AZEROTHDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Auth Server Down, Restarting: $datestring";
			open(OUTF, ">>$AZEROTHDIR/Auth_Server_Screen.log") || die "Unable to open $AZEROTHDIR/Auth_Server_Screen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $AZEROTHDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S AuthServer -d -U -m $AZEROTHDIR/acore.sh run-authserver");
		}
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
